### ISSUE TITLE
Stream (ReadStream) to Base64

### ISSUE THREAD

**Issue by Lesnock** [przemyslawpluta/extractd#4]
How can I convert the stream preview to Base64 without create the JPG file?

**Comment by przemyslawpluta** [comment]
@Lesnock shall I assume you'd like to receive base64 stream instead of current binary?

**Comment by przemyslawpluta** [comment]
https://github.com/przemyslawpluta/extractd/commit/4f9e737b3e7045870fae913051b147bef43964b6 available in **v2.1.0**
