### ISSUE TITLE
Extractd does not work with directories that contains accents

### ISSUE THREAD

**Issue by Lesnock** [przemyslawpluta/extractd#5]
When I try to use extractd with a file path that have accents (ó, for example), it does not find the file.

```javascript
const done = await extractd.generate('D:\\Fótos\\Image.CR2', {
    destination: '/temp/dir/'
 });

// Throws excepiton: 'File not found'
```

What can I do about it?

**Comment by przemyslawpluta** [comment]
[non-ASCII characters related](https://exiftool.org/forum/index.php?topic=12673.0)
